## In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow
More specifically, we're going to cover:
- Introduction to tensors
- Getting informations from tensors
- Manupulating tensors
- Tensors & NumPy
- Using@tf.function (a way to speed up your regular Python functions)
- Using GPUs with TensorFlow (or TPUs)
- Excercise to try for yourself

# Introduction to Tensors

In [1]:
# İmport TensorFlow
import tensorflow as tf
print(tf.__version__)

2.20.0


In [2]:
# Create testros with  tf.constant()
scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)

scalar.ndim #type:ignore

0

In [4]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of our vector
vector.ndim #type:ignore

1

In [6]:
# create a matrix (has more than 1 dimensions)
matrix = tf.constant([
    [10,7],
    [7,10]
    ])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim #type:ignore

2

In [8]:
# create another matrix
another_matrix = tf.constant([
    [10., 7.], [3., 2.], [8., 7.]
], dtype=tf.float16) # specify the data type with dtype


In [9]:
# what's the number of dimensions of another_matrix?
another_matrix.ndim #type:ignore

2

In [10]:
# lets create a tensor
tensor = tf.constant([
    [[1,2,3],
    [4,5,6]],

    [[7,8,9],
    [10,11,12]],

    [[13,14,15],
    [16,17,18]]
])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim # type: ignore

3

what we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* matrix: a 2-dimensional array of numbers
* Tensor an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

# Changeable & Unchangeable tensors

creating Tensors with tf.Variable

In [15]:
tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:
# Let's try change one of the elements in our changeable tensors

changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7) # type: ignore
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7) # type: ignore
changeable_tensor

# Creating random tensors