# Homework 1
Write a neural network that takes a single numerical input and predicts a single numerical output.

In [2]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.20.0'

In [3]:
X_ = np.arange(1, 20, 1, dtype="float32")
y = np.pow(X_,2)
X_,y


(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19.], dtype=float32),
 array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100., 121.,
        144., 169., 196., 225., 256., 289., 324., 361.], dtype=float32))

In [4]:
X_ = tf.constant(X_)
X = tf.expand_dims(X_, axis=-1)
y = tf.constant(y)
print(X)
print(y)

tf.Tensor(
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]
 [12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]], shape=(19, 1), dtype=float32)
tf.Tensor(
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121. 144. 169. 196.
 225. 256. 289. 324. 361.], shape=(19,), dtype=float32)


In [140]:
model_1 = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(15, activation="relu"),
    tf.keras.layers.Dense(25, activation="relu"),
    tf.keras.layers.Dense(1)
])


model_1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),
                loss=tf.keras.losses.mse,
                metrics=["mae"])


model_1.fit(X,y,epochs=155)

Epoch 1/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 760ms/step - loss: 30019.7441 - mae: 131.0639
Epoch 2/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 22401.2402 - mae: 109.6194
Epoch 3/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 10911.0107 - mae: 71.9198
Epoch 4/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 2358.4634 - mae: 44.5075
Epoch 5/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 16530.2891 - mae: 123.6085
Epoch 6/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 3583.9712 - mae: 54.3258
Epoch 7/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 2877.2812 - mae: 41.5916
Epoch 8/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 6404.7056 - mae: 54.8494
Epoch 9/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 8341.9033 - mae: 62.1823
Epoch 10/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 8145.1191 - mae: 61.3994
Epoch 11/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 6365.8491 - mae: 54.5735
Epoch 12/155
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 3884.6785 - mae: 4

In [141]:
pred = tf.constant([1.,2.,5.,20])
model_1.predict(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


array([[  0.8909094],
       [  4.319385 ],
       [ 25.007227 ],
       [391.4137   ]], dtype=float32)

# Homework 2
Example: House square footage and number of rooms → price estimate. You can create your own data, and the model can learn both features together.

In [18]:
import tensorflow as tf
import numpy as np

tf.__version__

'2.20.0'

In [19]:
home_X = tf.constant([[70,2],
                      [80,2],
                      [100,3],
                      [50,1],
                      [150,4],
                      [80,2],
                      [80,3],
                      [110,4],
                      [90,2],
                      [100,4]], dtype="float32")



# fiyatlar arasında korelasyon oluşturalım
price_list_y = []
price_y = tf.constant([])

for i in home_X:
    price_glitch = np.random.random(1)*5000
    price = np.array(i[0]*10000) + np.array(i[1]*15000) + np.array(price_glitch)
    price_list_y.append(price)

price_y = tf.constant(price_list_y)


def calculate_y_ground(home_X):
    _price_glitch = 5000
    _price = np.array(home_X[0][0]*10000) + np.array(home_X[0][1]*15000) + np.array(_price_glitch)
    return _price


print(price_y)
print(calculate_y_ground([[70,2]]))

tf.Tensor(
[[ 734879.87635862]
 [ 831041.65574389]
 [1045877.55620531]
 [ 517725.48759406]
 [1560057.23865481]
 [ 831133.60322199]
 [ 846757.5363007 ]
 [1162273.06096896]
 [ 930385.86128544]
 [1061750.90664844]], shape=(10, 1), dtype=float64)
735000


In [20]:
home_X

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[ 70.,   2.],
       [ 80.,   2.],
       [100.,   3.],
       [ 50.,   1.],
       [150.,   4.],
       [ 80.,   2.],
       [ 80.,   3.],
       [110.,   4.],
       [ 90.,   2.],
       [100.,   4.]], dtype=float32)>

In [21]:
model_2 = tf.keras.Sequential([
    tf.keras.layers.Dense(15),
    tf.keras.layers.Dense(20, activation="relu"),
    tf.keras.layers.Dense(25, activation="relu"),
    tf.keras.layers.Dense(1)
])


model_2.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
    loss = tf.keras.losses.MSE,
    metrics = ["mae"]
)

model_2.fit(home_X, price_y, epochs=150)


Epoch 1/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 745ms/step - loss: 977702420480.0000 - mae: 952143.1875
Epoch 2/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 977652023296.0000 - mae: 952118.6250
Epoch 3/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 977592451072.0000 - mae: 952089.6875
Epoch 4/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 977521213440.0000 - mae: 952055.0000
Epoch 5/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 977437065216.0000 - mae: 952014.0000
Epoch 6/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 977340334080.0000 - mae: 951966.8125
Epoch 7/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 977230233600.0000 - mae: 951913.1875
Epoch 8/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 977106305024.0000 - mae: 951852.8125
Epoch 9/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 976964419584.0000 - mae: 951783.6250
Epoch 10/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 976801366016.0000 - mae: 951704.1875
Epoch 11/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/st

In [22]:
pred = tf.constant([[70. ,3. ],[80., 3.]])

print("X: \n", pred)
print("\nExpected y: \n", calculate_y_ground(pred))


print("\npredicted y:")
model_2.predict(pred)

X: 
 tf.Tensor(
[[70.  3.]
 [80.  3.]], shape=(2, 2), dtype=float32)

Expected y: 
 750000.0

predicted y:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[738109.56],
       [838648.06]], dtype=float32)

# Homework 3
Use real dataset

In [10]:
import tensorflow as tf
import numpy as np

tf.__version__

'2.20.0'

In [11]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
data = fetch_california_housing()

print(data.data)
print(data.target)
print(len(data.data)) #20640 sample

X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.3)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# daha derin bi model oluşturalım

model_3 = tf.keras.Sequential([
    tf.keras.layers.Dense(15),
    tf.keras.layers.Dense(30, activation="relu"),
    tf.keras.layers.Dense(50, activation="relu"),
    tf.keras.layers.Dense(1),
])

model_3.compile(
    optimizer = tf.keras.optimizers.Adam(),
    loss= tf.keras.losses.MSE,
    metrics = ["mae"]
)

callback = tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)
model_3.fit(X_train, y_train, epochs=200, callbacks=[callback], validation_data=(X_test, y_test))

model_3.evaluate(X_test, y_test)

[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]
[4.526 3.585 3.521 ... 0.923 0.847 0.894]
20640
Epoch 1/200
452/452 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 1.2646 - mae: 0.7256 - val_loss: 0.5836 - val_mae: 0.4956
Epoch 2/200
452/452 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4267 - mae: 0.4653 - val_loss: 0.4668 - val_mae: 0.4642
Epoch 3/200
452/452 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3872 - mae: 0.4429 - val_loss: 0.4490 - val_mae: 0.4381
Epoch 4/200
452/452 ━━━━━━━━━━━━

[0.2946099638938904, 0.3628535270690918]

# Homework 4
save the model and reload it outputs must be same

In [13]:
import tensorflow as tf
import numpy as np
import os
tf.__version__

'2.20.0'

In [14]:
model_3.evaluate(X_test, y_test)

194/194 ━━━━━━━━━━━━━━━━━━━━ 0s 714us/step - loss: 0.2946 - mae: 0.3629


[0.2946099638938904, 0.3628535270690918]

In [15]:
filepath = os.path.join(os.getcwd(), "../model_3.keras")
model_3.save(filepath = filepath)

loaded_model = tf.keras.models.load_model(filepath)

loaded_model.evaluate(X_test, y_test)

194/194 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step - loss: 0.2946 - mae: 0.3629


[0.2946099638938904, 0.3628535270690918]

# Homework 5
Transform what you've done so far into a Streamlit application. Users enter square footage and number of rooms, the model makes an estimate, and the price appears on the screen. Upload and use the model you've saved.

**Note! Streamlit doesn't work with .ipynb files; use it in a .py file.**

In [44]:
import tensorflow as tf
import streamlit as st
import os


In [ ]:
path = os.path.join(os.getcwd(),"Regression homework","model_2.keras")

model = tf.keras.models.load_model(path)

st.title("House Price Predictor")

sq_meters = st.text_input("Metrekare girin", 80)

n_of_room = st.text_input("oda sayısı girin", 3)

if sq_meters and n_of_room:
    if not sq_meters.isdigit() or not n_of_room.isdigit():
        st.error("Enter a number")

    sq_meters = float(sq_meters)
    n_of_room = float(n_of_room)
    pred = tf.constant([[sq_meters, n_of_room]])
    st.markdown("---")
    st.markdown("**Price:**")
    st.text(f"$ {model.predict(pred)[0][0]:,.0f}")
